USE MASTER
GO

CREATE LOGIN localhost1 WITH PASSWORD = 'MeLLfMA1wBlJCzSGZhkO';
CREATE LOGIN ropsten1 WITH PASSWORD = 'MgOumZZ1LVbV5gSfen3M';
CREATE LOGIN kovan1 WITH PASSWORD = 'm4753ct9kYMospex';
CREATE LOGIN rinkeby1 WITH PASSWORD = 'rzNk9PyskZg0jLIl';
CREATE LOGIN main1 WITH PASSWORD = 'ix2tjLkUEmPJ2Ah6';